ddd = int(input())

if ddd == 61: print('Brasilia')
elif ddd == 71: print('Salvador')
if ddd == 11: print('Sao Paulo')
if ddd == 21: print('Rio de Janeiro')
if ddd == 32: print('Juiz de Fora')
if ddd == 19: print('Campinas')
if ddd == 27: print('Vitoria')
if ddd == 31: print('Belo Horizonte')
else: print('DDD nao cadastrado')